# 2022年度第3ターム「実験数学C」 第04回 10/25(火)4限

In [10]:
# 必要な外部モジュールをインストールする
!pip install numpy

In [11]:
# 必要なモジュールをインポートする
import numpy as np

## 以下の行列の固有値・固有ベクトルを求める

### 1. $\begin{pmatrix}2 & -2 \\ -1 & 3\end{pmatrix}$.

固有値は $1, 4$ ，固有ベクトルはそれぞれ $s(-0.89442719,-0.4472136), t(0.70710678,-0.70710678)\ (s, t \text{は任意定数})$ ．

In [12]:
# 2×2正方行列を定義
a = np.array([[2, -2], [-1, 3]])

# aの固有値と固有ベクトル
# インデクス0に固有値，インデクス1に固有ベクトルが格納される
a_eig = np.linalg.eig(a)

# 固有値を表示
print("固有値 {}".format(a_eig[0]))

# 固有ベクトルを表示
print("固有ベクトル {}".format(a_eig[1]))
# (-0.89442719,-0.4472136)が固有値1に，(0.70710678,-0.70710678)が固有値4に対応する

固有値 [1. 4.]
固有ベクトル [[-0.89442719  0.70710678]
 [-0.4472136  -0.70710678]]


### 2. $\begin{pmatrix}2 & 1 & 1 \\ 1 & 2 & 1 \\ 1 & 1 & 2\end{pmatrix}$.

固有値は $4, 1$ (重解) ，固有ベクトルはそれぞれ $t(1, 1, 1), a(1, 0, -1) + b(0, 1, -1)\ (t, a, b \text{は任意定数})$ ．

In [13]:
# 3×3行列を行ごとに入力
arr = np.array([[2, 1, 1] , [1, 2, 1] , [1, 1, 2]])
# 行列を表示
print(arr)
# 固有値，固有ベクトルを計算
w, v = np.linalg.eig(arr)
# 固有値，固有ベクトルを表示
print(w)
print(v)
# 固有ベクトルが固有値4の時t(1,1,1) (tは任意定数) となり，1の時不定形となるためa(1,0,-1) + b(0,1,-1)と表現できる

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[1. 4. 1.]
[[-0.81649658  0.57735027  0.381008  ]
 [ 0.40824829  0.57735027 -0.81590361]
 [ 0.40824829  0.57735027  0.43489561]]


### 3. $\begin{pmatrix}1 & 1 & 0 \\ 1 & 0 & 1 \\ 1 & -1 & -1\end{pmatrix}$.

固有値は $1.67169988, -0.83584994 \pm j1.04686932$ ，固有ベクトルはそれぞれ $(-0.82583158, -0.55471098, -0.10147869), (0.05335901 \mp j0.26581798, 0.18031755 \pm j0.54386184, -0.7734297)\ (j \text{は虚数単位，} a, b, c \text{は任意定数})$ ．

In [14]:
# 3×3行列を行ごとに入力
arr = np.array([[1, 1, 0] , [1, 0, 1] , [1, -1, -1]])
# 行列を表示
print(arr)
# 固有値，固有ベクトルを計算
w, v = np.linalg.eig(arr)
# 固有値，固有ベクトルを表示
print(w)
print(v)
# pythonでは複素数表現で用いられる虚数iがjとして表現されることに注意

[[ 1  1  0]
 [ 1  0  1]
 [ 1 -1 -1]]
[ 1.67169988+0.j         -0.83584994+1.04686932j -0.83584994-1.04686932j]
[[-0.82583158+0.j          0.05335901-0.26581798j  0.05335901+0.26581798j]
 [-0.55471098+0.j          0.18031755+0.54386184j  0.18031755-0.54386184j]
 [-0.10147869+0.j         -0.7734297 +0.j         -0.7734297 -0.j        ]]
